#!/bin/bash

umask 022
grep -q 7437 /usr/local/sbin/mount-crypt.sh \
	&& sed -i s,port=7437,port=7445, /usr/local/sbin/mount-crypt.sh
mkdir -p /mnt/ntfs{1,2}
if grep -q aes /proc/cpuinfo; then
	mount -rtntfs -ouid=1000,gid=100 /dev/sda1 /mnt/ntfs1
	mount -rtntfs -ouid=1000,gid=100 /dev/sda2 /mnt/ntfs2
fi
