#!/bin/bash

umask 022
mkdir -p /mnt/ntfs{1,2}
if grep -q aes /proc/cpuinfo; then
	mount -rtntfs -ouid=172504,gid=5000 /dev/sda1 /mnt/ntfs1
	mount -rtntfs -ouid=172504,gid=5000 /dev/sda2 /mnt/ntfs2
fi
