#!/bin/bash

umask 022
rm -f /usr/bin/helper
if ! [[ -e /usr/local/bin/helper ]]; then
	cat >/usr/local/bin/helper <<'EOF'
#!/usr/bin/python3

import os
import subprocess
from tkinter import *
import types

root = Tk()
root.title( 'Helper' )
root.option_add( '*Font', 'Helvetica 18' )

def stateful( func ):
	func.state = IntVar()
	return func

def tcb_display( self, i ):
	cb = self.acb_display[ i ]
	state = cb.state.get()
	if state != 1 and os.system( 'xrandr -q | grep -q ^%s.connected' % cb.display ):
		state = 1
		cb.state.set( state )
	os.system( 'xrandr --output LVDS-0 --auto --output %s ' % cb.display +
			   ( '--auto --left-of LVDS-0',
				 '--off',
				 '--auto --right-of LVDS-0' )[ state ] )

class Application( Frame ):
	@stateful
	def cb_dpms( self ):
		os.system( 'xset dpms 600 1200 1800'
				   if self.cb_dpms.state.get() else
				   'xset dpms 0 0 0' )

	def cb_kill( self ):
		os.system( 'pgrep pulseaudio | xargs -r kill' )

	def cb_suspend( self ):
		for cb, state in ( self.cb_dpms, 1 ),:
			if state != cb.state.get():
				cb.state.set( state )
				cb()
		self.w_reset_state()
		os.system( 'sudo /etc/init.d/cryptnmount restart; sudo pm-suspend' )
		self.w_reset_state()

	def w_init_state( self ):
		randr = subprocess.getoutput( 'xrandr -q' )
		displays = [] if -1 == randr.find( 'LVDS-0' ) else \
			[ x for x in ( x.split( ' ', 1 )[ 0 ] for x in randr.split( '\n' ) )
				if x not in ( '', 'VGA-0', 'LVDS-0', 'Screen' ) ]
		def displayful( i, func ):
			func.display = displays[ i ]
			return types.MethodType( stateful( func ), self )
		self.acb_display = tuple( map(
			lambda i: displayful( i, lambda self: tcb_display( self, i ) ),
			range( min( 2, len( displays ) ) ) ) )

	def w_reset_state( self ):
		self.cb_dpms.state.set( not not os.system( 'xset q | grep -q Standby:.0' ) )
		for cb in self.acb_display:
			state = os.system(
				'''
				line=`xrandr -q | grep ^%s`
				if [[ $line ]]; then
					if grep -q 'discon.*+' <<<$line; then
						xrandr --output LVDS-0 --auto --output %s --off
						exit 1
					fi
					grep -q + <<<$line || exit 1
					offset=`cut -d+ -f2 <<<$line`
					exit $((2 * ! ! offset))
				else
					exit -1
				fi
				''' % ( ( cb.display, ) * 2 ) ) // 256
			assert 0 <= state < 3
			cb.state.set( state )

	def w_create( self ):
		Checkbutton( self, text='DPMS', variable=self.cb_dpms.state,
					 command=self.cb_dpms ).grid( columnspan=3 )
		for i, cb in enumerate( self.acb_display ):
			for j, t in enumerate( ( 'L', 'N', 'R' ) ):
				Radiobutton( self, text=t, value=j, variable=cb.state,
							 command=cb ).grid( row=1 + i, column=j )
		Button( self, text='Kill Pulse', command=self.cb_kill ).grid(
			columnspan=3, sticky=W+E )
		Button( self, text='Suspend', command=self.cb_suspend ).grid(
			columnspan=3, sticky=W+E )

	def __init__( self, master ):
		Frame.__init__( self, master )
		self.pack()
		self.w_init_state()
		self.w_reset_state()
		self.w_create()

app = Application( master=root )
app.mainloop()
EOF
	chmod +x /usr/local/bin/helper
	sed -i 's;^sigaev.*;Cmnd_Alias NOTTY=/usr/sbin/pm-suspend,/etc/init.d/cryptnmount\nDefaults requiretty\nDefaults!NOTTY !requiretty\nsigaev ALL=NOPASSWD:ALL;' /etc/sudoers
	cat >/usr/local/bin/dev-rsync <<'EOF'
#!/usr/bin/python3

import os
import sys

SIZE_BLOCK = 131072

size_f = os.stat( sys.argv[ 2 ] ).st_size
assert 0 == size_f % SIZE_BLOCK
num_written_blocks = 0
with open( sys.argv[ 1 ], 'rb' ) as f_a:
	with open( sys.argv[ 2 ], 'r+b' ) as f_b:
		for i_block in range( size_f // SIZE_BLOCK ):
			buf_a, buf_b = ( f.read( SIZE_BLOCK ) for f in ( f_a, f_b ) )
			assert SIZE_BLOCK == len( buf_a ) == len( buf_b )
			if buf_a != buf_b:
				f_b.seek( i_block * SIZE_BLOCK )
				assert SIZE_BLOCK == f_b.write( buf_a )
				f_b.seek( ( i_block + 1 ) * SIZE_BLOCK )
				num_written_blocks += 1

print( 'Overwritten %.3f Mb of %.3f Mb' % (
	num_written_blocks * SIZE_BLOCK / 1024 ** 2,
	size_f / 1024 ** 2 ) )
EOF
	chmod +x /usr/local/bin/dev-rsync
fi
