#!/bin/bash

umask 022
a=
b=
grep -q 7437 /usr/local/sbin/mount-crypt.sh && a=1
grep -q ssd /etc/fstab || b=1

[[ $a || $b ]] && mount -woremount /
[[ $a ]] && sed -i s,port=7437,port=7445, /usr/local/sbin/mount-crypt.sh
[[ $b ]] && sed -i '/LABEL=\(root\|home\)/s/\(noatime[^ ]*\) \{26\}/\1,ssd,discard,compress=zlib/' /etc/fstab
[[ $a || $b ]] && mount -roremount /
